#!/bin/bash
tmp_dir="/tmp/xmonad/quotes"

if [ ! -d $tmp_dir ]; then
        mkdir -p $tmp_dir
fi
cp ~/.config/eww/dashboard/scripts/quotes.json /tmp/xmonad/quotes/ && exec  ~/.config/eww/dashboard/scripts/quotes
