#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.screenlayout/resolutions.sh &

feh --bg-scale ~/Downloads/wallpaper.jpg &

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

$HOME/.config/polybar/launch.sh --colorblocks

picom &

# bspc monitor -d 一  二  三  四  五  六  七  八
bspc monitor -d I II III IV V VI VII VIII 

bspc config border_width         0
bspc config window_gap          12

bspc config normal_border_color "#8ba3f4"
bspc config focused_border_color "#ffa1f7"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
