require('plugins')
require('keybindings')
require('options')
vim.cmd[[colorscheme tokyonight]]
require('treesitter-config')
require('presence-config')
require('autopairs-config')
require('lualine-config')
require('nvim-tree-config')
require('bufferline-config')
require('telescope-config')
require('whichkey-config')
require('toggleterm-config')
require('lsp')
